---
Name: MinifierConfig
After:
  - requestprocessors
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        HTMLMinifierMiddleware: '%$DorsetDigital\SSMinifier\Middleware'
